### ISSUE TITLE
ios 13.3 still has that big gap

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#307] opened 2020-06-15 21:33 UTC
To install ios 13.3 simulator: https://stackoverflow.com/questions/58072572/how-to-run-a-different-version-of-the-ios-simulator-on-xcode-11

<img width="1355" alt="Screen Shot 2020-06-15 at 2 33 26 PM" src="https://user-images.githubusercontent.com/1427524/84708362-349b7a00-af15-11ea-876a-91b817d82851.png">

**Comment by finben** [comment] 2020-06-15 23:31
Bro, this issue is bad news bears.... Basically, it has to do with our NavigationView containing the TabView within our homeContainer. The problem is if we put individual navigationViews within each of the tabs as many users would suggest then we are going to be showing the Tabs on every single page of our app. As of now this is not yet supported in SwiftUI.  https://stackoverflow.com/questions/58067390/hide-tabview-after-clicking-on-a-navigationlink-in-swiftui

I am not sure what to do. We can hope that WWDC 2020 gives us a .hidetabview option which they might do similiar to what they have for navTitle. 

Another, potential solution would be we fake the tabView. And instead of a real tab view we use Buttons in an HStack that essentially just do NavigationBarLink. 

In the mean time I am going to submit a PR that at least shrinks that extra whitespace some.

**Comment by skywalkerdude** [comment] 2020-06-16 00:07
@finben I'm a little confused. I don't understand that that link is saying. It talks about hiding the tab. But it doesn't talk about like the big gap at the top. Why is it that the NavigationView causes the gap?

**Comment by finben** [comment] 2020-06-16 00:30
It seems like a bug to me that got resolved in later versions which occurs whenever you place a TabView within a navigationView. It is because at this point Apple only really planned for people to be using navigationView within TabView instead of the other way around.

**Closed** 2020-07-05 05:33 UTC
